package hxdna

import (
	"encoding/base64"
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"github.com/go-resty/resty/v2"
)

// BootstrapPayload is decoded from the base64 bootstrap token generated by the control plane.
type BootstrapPayload struct {
	URL         string `json:"url"`
	Token       string `json:"token"`
	InstanceID  string `json:"instance_id"`
	OrgID       string `json:"org_id"`
	Environment string `json:"environment"`
}

// EnrollRequest holds the information the worker provides at enrollment time.
type EnrollRequest struct {
	Name         string
	Description  string
	Hostname     string
	Version      string
	WorkerPrompt string
}

// EnrollResult holds the data returned by the control plane after a successful enrollment.
type EnrollResult struct {
	WorkerID   string
	Name       string
	EnrolledAt string
	NatsURL    string
}

// DecodeBootstrap decodes a base64 bootstrap token into a BootstrapPayload.
func DecodeBootstrap(token string) (*BootstrapPayload, error) {
	raw, err := base64.StdEncoding.DecodeString(token)
	if err != nil {
		raw, err = base64.RawStdEncoding.DecodeString(token)
		if err != nil {
			return nil, fmt.Errorf("invalid bootstrap token: %w", err)
		}
	}
	var bp BootstrapPayload
	if err := json.Unmarshal(raw, &bp); err != nil {
		return nil, fmt.Errorf("malformed bootstrap payload: %w", err)
	}
	return &bp, nil
}

// Enroll registers this worker with the control plane using the decoded bootstrap payload.
func Enroll(bp *BootstrapPayload, req EnrollRequest) (*EnrollResult, error) {
	type triagePromptItem struct {
		Name        string `json:"name"`
		Description string `json:"description"`
		Content     string `json:"content"`
	}
	type requestBody struct {
		Token         string             `json:"token"`
		Name          string             `json:"name,omitempty"`
		Description   string             `json:"description,omitempty"`
		Environment   string             `json:"environment,omitempty"`
		Hostname      string             `json:"hostname"`
		Version       string             `json:"version"`
		TriagePrompts []triagePromptItem `json:"triage_prompts,omitempty"`
	}
	type responseBody struct {
		Data struct {
			WorkerID   string `json:"worker_id"`
			Name       string `json:"name"`
			EnrolledAt string `json:"enrolled_at"`
			NatsURL    string `json:"nats_url"`
		} `json:"data"`
		Message string `json:"message"`
	}

	body := requestBody{
		Token:       bp.Token,
		Name:        req.Name,
		Description: req.Description,
		Environment: bp.Environment,
		Hostname:    req.Hostname,
		Version:     req.Version,
	}
	if req.WorkerPrompt != "" {
		body.TriagePrompts = []triagePromptItem{
			{
				Name:        "Worker Capability Prompt",
				Description: "Describes what this worker does and its available commands",
				Content:     req.WorkerPrompt,
			},
		}
	}

	client := resty.New().SetTimeout(30 * time.Second)
	var resp responseBody
	r, err := client.R().
		SetBody(body).
		SetResult(&resp).
		Post(strings.TrimRight(bp.URL, "/") + "/workers/enroll")
	if err != nil {
		return nil, fmt.Errorf("enrollment request failed: %w", err)
	}
	if r.StatusCode() != 200 && r.StatusCode() != 201 {
		return nil, fmt.Errorf("enrollment failed (%d): %s", r.StatusCode(), r.String())
	}
	if resp.Data.WorkerID == "" {
		return nil, fmt.Errorf("control plane returned an empty worker_id — check the bootstrap token and try again")
	}

	return &EnrollResult{
		WorkerID:   resp.Data.WorkerID,
		Name:       resp.Data.Name,
		EnrolledAt: resp.Data.EnrolledAt,
		NatsURL:    resp.Data.NatsURL,
	}, nil
}

// CheckApproval checks the worker's enrollment status with the control plane.
// Returns "pending", "active", or "revoked".
func CheckApproval(s *State) (string, error) {
	client := resty.New().SetTimeout(10 * time.Second)
	var result struct {
		Data struct {
			Status string `json:"status"`
		} `json:"data"`
	}
	resp, err := client.R().
		SetResult(&result).
		Get(strings.TrimRight(s.ControlURL, "/") + "/workers/" + s.WorkerID + "/status")
	if err != nil {
		return "", fmt.Errorf("could not reach control plane: %w", err)
	}
	if resp.StatusCode() == 404 {
		return "", fmt.Errorf("worker not found — re-enroll with: worker enroll <bootstrap>")
	}
	if resp.StatusCode() >= 400 {
		return "", fmt.Errorf("control plane returned %d", resp.StatusCode())
	}
	if result.Data.Status == "" {
		return "", fmt.Errorf("empty status from control plane")
	}
	return result.Data.Status, nil
}
